development:
  adapter: async
 
test:
  adapter: async
 
production:
  adapter: postgresql
  url: postgres://mpwertwertzwzyinkk:GPNkY1wKnMasdfasdtrs6jmO8-0BT@ec2-42-123-007-111.compute-1.amazonaws.com:1235/a0s987645usdf6
  channel_prefix: appname_production
